### ISSUE TITLE
Will this work on Flutter mobile Android/IOS?

### ISSUE THREAD

**Issue by Catsvilles** [luanpotter/dart_web_audio#3]
Hi, sorry, very new to Flutter, trying to find an advanced Audio API for my mobile app. Something tells me this package is still bound only to the web and browsers? :)

**Comment by luanpotter** [comment]
Yes, it is specifically designed to bridge the web API. Take a look at [audioplayers](https://github.com/luanpotter/audioplayers) for a complete, advanced API that works on android, ios, macos, and web :)
